version: '3'

services: 
  web:
    build: .
    image: mytodo
    env_file:
      - ./.env.dev
    command: python manage.py runserver 0.0.0.0:${PORT}
    ports: 
      - 8000:8000
    volumes:
      - .:/usr/src/app/
    depends_on: 
      - redis
      - db
  redis:
    image: redis:alpine
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data:

