version: '3'

services: 
  web:
    build: .
    image: mytodo
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    volumes:
      - .:/usr/src/app/
    depends_on: 
      - redis
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A todo worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on: 
      - redis
  celery-beat:
    build: .
    command: celery -A todo beat -l info
    volumes: 
      - .:/usr/src/app/
    depends_on: 
      - redis
