version: '3'

services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: mytodo_prod
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:${PORT}
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on: 
      - redis
      - db
  redis:
    image: redis:alpine
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8000:80
    depends_on: 
      - web

volumes:
  postgres_data:      
  static_volume: