# Generated by Django 3.1.6 on 2021-03-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20210303_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='reddit.posts')),
            ],
        ),
    ]
