# Generated by Django 3.1.6 on 2021-03-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_auto_20210304_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_disliked',
            field=models.BooleanField(default=False),
        ),
    ]
