# Generated by Django 3.1.6 on 2021-03-22 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit', '0010_auto_20210319_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.CharField(choices=[('true', 'true'), ('false', 'false'), ('none', 'none')], max_length=20)),
                ('is_disliked', models.CharField(choices=[('true', 'true'), ('false', 'false'), ('none', 'none')], max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.comment')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
